// Sample data for The Lovely Loo Marketing Dashboard
// In production, this would pull from Gravity Forms API, Google Ads API, and Facebook Ads API

export const kpiData = {
  totalLeads: 247,
  totalLeadsChange: 12.5,
  totalAdSpend: 8420,
  totalAdSpendChange: -3.2,
  costPerLead: 34.09,
  costPerLeadChange: -14.1,
  conversionRate: 4.8,
  conversionRateChange: 8.3,
  websiteLeads: 142,
  websiteLeadsChange: 18.2,
  phoneLeads: 105,
  phoneLeadsChange: 5.7,
}

export const monthlyLeadsData = [
  { month: "Sep", website: 18, googleAds: 12, facebookAds: 8 },
  { month: "Oct", website: 22, googleAds: 15, facebookAds: 11 },
  { month: "Nov", website: 16, googleAds: 10, facebookAds: 9 },
  { month: "Dec", website: 12, googleAds: 8, facebookAds: 6 },
  { month: "Jan", website: 20, googleAds: 14, facebookAds: 10 },
  { month: "Feb", website: 28, googleAds: 18, facebookAds: 14 },
]

export const adSpendData = [
  { month: "Sep", google: 1200, facebook: 800 },
  { month: "Oct", google: 1400, facebook: 950 },
  { month: "Nov", google: 1100, facebook: 700 },
  { month: "Dec", google: 900, facebook: 600 },
  { month: "Jan", google: 1350, facebook: 850 },
  { month: "Feb", google: 1500, facebook: 970 },
]

export const leadSourceBreakdown = [
  { name: "Website (Gravity Forms)", value: 142, fill: "var(--color-chart-1)" },
  { name: "Google Ads", value: 62, fill: "var(--color-chart-2)" },
  { name: "Facebook Ads", value: 43, fill: "var(--color-chart-3)" },
]

export const googleAdsMetrics = {
  spend: 7450,
  impressions: 184200,
  clicks: 3820,
  ctr: 2.07,
  conversions: 62,
  costPerConversion: 120.16,
  campaigns: [
    {
      name: "Restroom Trailer Rentals - FL",
      spend: 2850,
      impressions: 68400,
      clicks: 1480,
      conversions: 24,
      ctr: 2.16,
    },
    {
      name: "Wedding Portable Restrooms",
      spend: 1920,
      impressions: 52100,
      clicks: 1120,
      conversions: 19,
      ctr: 2.15,
    },
    {
      name: "Event Restroom Trailers - GA",
      spend: 1380,
      impressions: 38200,
      clicks: 740,
      conversions: 11,
      ctr: 1.94,
    },
    {
      name: "Luxury Porta Potty Near Me",
      spend: 1300,
      impressions: 25500,
      clicks: 480,
      conversions: 8,
      ctr: 1.88,
    },
  ],
}

export const facebookAdsMetrics = {
  spend: 4870,
  impressions: 245600,
  clicks: 5120,
  ctr: 2.08,
  conversions: 43,
  costPerConversion: 113.26,
  campaigns: [
    {
      name: "Wedding Season Promo",
      spend: 1850,
      impressions: 92400,
      clicks: 2100,
      conversions: 18,
      ctr: 2.27,
    },
    {
      name: "Event Planners Lookalike",
      spend: 1420,
      impressions: 78200,
      clicks: 1540,
      conversions: 12,
      ctr: 1.97,
    },
    {
      name: "St. Augustine Local Reach",
      spend: 980,
      impressions: 48600,
      clicks: 920,
      conversions: 8,
      ctr: 1.89,
    },
    {
      name: "Retargeting - Site Visitors",
      spend: 620,
      impressions: 26400,
      clicks: 560,
      conversions: 5,
      ctr: 2.12,
    },
  ],
}

export const recentLeads = [
  {
    id: 1,
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "(904) 555-0142",
    source: "Website",
    eventType: "Wedding",
    eventDate: "2026-04-15",
    location: "St. Augustine, FL",
    status: "New",
    createdAt: "2026-02-22",
  },
  {
    id: 2,
    name: "James Parker",
    email: "jparker@email.com",
    phone: "(912) 555-0198",
    source: "Google Ads",
    eventType: "Corporate Event",
    eventDate: "2026-03-28",
    location: "Savannah, GA",
    status: "Contacted",
    createdAt: "2026-02-21",
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "(904) 555-0267",
    source: "Facebook Ads",
    eventType: "Festival",
    eventDate: "2026-05-10",
    location: "Jacksonville, FL",
    status: "Qualified",
    createdAt: "2026-02-20",
  },
  {
    id: 4,
    name: "Michael Thompson",
    email: "mthompson@email.com",
    phone: "(386) 555-0334",
    source: "Website",
    eventType: "Wedding",
    eventDate: "2026-06-22",
    location: "Palm Coast, FL",
    status: "New",
    createdAt: "2026-02-19",
  },
  {
    id: 5,
    name: "Laura Chen",
    email: "lchen@email.com",
    phone: "(904) 555-0411",
    source: "Google Ads",
    eventType: "Construction",
    eventDate: "2026-03-05",
    location: "St. Augustine, FL",
    status: "Converted",
    createdAt: "2026-02-18",
  },
  {
    id: 6,
    name: "David Wright",
    email: "dwright@email.com",
    phone: "(912) 555-0088",
    source: "Website",
    eventType: "Outdoor Party",
    eventDate: "2026-04-02",
    location: "Brunswick, GA",
    status: "Contacted",
    createdAt: "2026-02-17",
  },
  {
    id: 7,
    name: "Ashley Brooks",
    email: "abrooks@email.com",
    phone: "(904) 555-0523",
    source: "Facebook Ads",
    eventType: "Wedding",
    eventDate: "2026-05-30",
    location: "Ponte Vedra, FL",
    status: "New",
    createdAt: "2026-02-16",
  },
  {
    id: 8,
    name: "Robert Kim",
    email: "rkim@email.com",
    phone: "(386) 555-0199",
    source: "Website",
    eventType: "Remodel",
    eventDate: "2026-03-15",
    location: "Daytona Beach, FL",
    status: "Qualified",
    createdAt: "2026-02-15",
  },
]

export const weeklyLeadsData = [
  { day: "Mon", leads: 5 },
  { day: "Tue", leads: 8 },
  { day: "Wed", leads: 6 },
  { day: "Thu", leads: 9 },
  { day: "Fri", leads: 12 },
  { day: "Sat", leads: 4 },
  { day: "Sun", leads: 3 },
]
